# Generated by Django 4.2.14 on 2024-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(null=True)),
                ('fullpath', models.TextField(null=True, unique=True)),
                ('extention', models.TextField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('ctime', models.IntegerField(null=True)),
                ('mtime', models.IntegerField(null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('piece', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(null=True)),
                ('fullpath', models.TextField(null=True)),
                ('extention', models.TextField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('ctime', models.IntegerField(null=True)),
                ('mtime', models.IntegerField(null=True)),
                ('md5', models.CharField(max_length=32, null=True, unique=True)),
                ('facture_type', models.TextField(null=True)),
                ('facture_author', models.TextField(null=True)),
                ('facture_client', models.TextField(null=True)),
                ('facture_identifier', models.TextField(null=True)),
                ('facture_date', models.DateTimeField(null=True)),
                ('facture_libelle', models.TextField(null=True)),
                ('facture_prix_ht', models.FloatField(null=True)),
                ('facture_prix_tax', models.FloatField(null=True)),
                ('facture_prix_ttc', models.FloatField(null=True)),
                ('facture_devise', models.TextField(null=True)),
                ('paiement_comment', models.TextField(null=True)),
                ('paiement_date', models.DateTimeField(null=True)),
                ('paiement_proof', models.TextField(null=True)),
                ('banque', models.IntegerField(null=True)),
                ('exercice_comptable', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('raw', models.TextField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('type', models.TextField(null=True)),
                ('banque_account', models.TextField(null=True)),
                ('rdate', models.DateTimeField(null=True)),
                ('vdate', models.DateTimeField(null=True)),
                ('label', models.TextField(null=True)),
                ('piece', models.IntegerField(null=True)),
                ('ctime', models.IntegerField(null=True)),
                ('mtime', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('date', 'raw')},
            },
        ),
    ]
